# Default values for qtest-launch app.

reloader:
  enabled: false

secrets:
  enabled: true

image:
  repository: qasymphony/launch
  pullPolicy: IfNotPresent
  tag: "1.6.5"

deployment:
  annotations: {}

service:
  type: LoadBalancer
  port: 3080
  targetPort: 3080
  servicename: qtest-launch-service

qTestLaunch:
  qTestLaunchDBName: qtest
  qTestLaunchDBUserName: postgres
  qTestLaunchDBPwd: Y2hhbmdlbWU=
  qTestLaunchDBHostName: postgres.local
  qTestLaunchRootURL: https://launch.local
  qTestLaunchQTestURL: https://nephele.qtest.local
  qTestLaunchNodeTLSRejectUnAuthorized: "0"
  qTestLaunchTCPWD: "qTest"
  qTestLaunchPort: "3080"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  canary:
    annotations: {}
  labels: {}
  hosts:
    - launch.local
  paths:
    - /
  extraPaths:
    []
  tls:
    []
  https: false

# VPA values
vpaAutoscaling:
  enabled: false
  updatePolicy:
    updateMode: "Off"

# HPA values
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  healthApiPath: /health-check
  periodSeconds: 30
  failureThreshold: 4
  targetCPUUtilizationPercentage: 85
  targetMemoryUtilizationPercentage: 85
