apiVersion: v1
kind: Service
metadata:
  name: qtest-insights-etl-service
  labels:
    app: qtest-insights-etl
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: qtest-insights-etl
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
