# Default values for qtest-insights-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
reloader:
  enabled: false

secrets:
  enabled: true

replicaCount: 1
image:
  repository: qasymphony/insights-etl
  pullPolicy: IfNotPresent
  tag: "e287a47"

deployment:
  annotations: {}

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080
  servicename: qtest-insights-etl-service

qTestInsightsEtl:
  qTestLogPath: /logs
  qTestUpdateDB: true
  qTestInsightsEtlDBName: qtest
  qTestInsightsEtlDBUser: postgres
  qTestInsightsEtlDBPassword: cG9zdGdyZXM=
  qTestInsightsEtlDBHost: postgres.local
  qTestInsightsEtlWriteQTestDBName: qtest
  qTestInsightsEtlWriteQTestDBUser: postgres
  qTestInsightsEtlWriteQTestDBPassword: cG9zdGdyZXM=
  qTestInsightsEtlWriteQTestDBHost: postgres.local
  qTestInsightsEtlSessionDBName: sessions
  qTestInsightsEtlSessionDBUser: postgres
  qTestInsightsEtlSessionDBPassword: cG9zdGdyZXM=
  qTestInsightsEtlSessionDBHost: postgres.local

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  canary:
    annotations: {}
  labels: {}
  hosts:
    - insights-etl.local
  paths:
    - /
  extraPaths:
    []
  tls:
    []
  https: false

persistence:
  enabled: false
  ## Set annotations on pvc
  annotations: {}

  ## Specify an existing volume claim instead of creating a new one.
  ## When using this option all following options like storageClass, accessMode and size are ignored.
  # existingClaim:

  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass:
  accessMode: ReadWriteOnce
  size: 5Gi

  ## Specify extra volumes. Refer to ".spec.volumes" specification : https://kubernetes.io/fr/docs/concepts/storage/volumes/
  volumes: []
  ## Specify extra mounts. Refer to ".spec.containers.volumeMounts" specification : https://kubernetes.io/fr/docs/concepts/storage/volumes/
  mounts: []

# VPA values
vpaAutoscaling:
  enabled: false
  updatePolicy:
    updateMode: "Off"

# HPA values
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  healthApiPath: /ping
  targetPort: 8765
  periodSeconds: 30
  failureThreshold: 4
  targetCPUUtilizationPercentage: 85
  targetMemoryUtilizationPercentage: 85
