# Default values for scenario App.

image:
  repository: qasymphony/scenario
  pullPolicy: IfNotPresent
  tag: "3.3.4"

annotations: {}

service:
  type: LoadBalancer
  port: 6080
  targetPort: 6080
  servicename: qtest-scenario-service
  annotations: {}

qTestScenario:
  qTestScenarioDBConnection: postgresql://postgres:changeme@postgres.local/scenario
  qTestScenarioPort: "6080"
  qTestScenarioLocalBaseURL: http://scenario.container-dev.qtestdev.com
  qTestScenarioNodeTLSRejectUnAuthorized: "0"
  qTestScenarioNodeEnvironment: production
  qTestScenarioRefreshTokenSecret: ""
  qTestScenarioAppKeyDescriptor: ""
  qTestScenarioQTestURL: http://qtestdev1.container-dev.qtestdev.com

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  canary:
    annotations: {}
  labels: {}
  hosts:
    - scenario.container-dev.qtestdev.com
  paths:
    - /
  extraPaths:
    []
  tls:
    []
  https: false

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  healthApiPath: /atlassian-connect.json
  periodSeconds: 30
  failureThreshold: 4
  targetCPUUtilizationPercentage: 85
  targetMemoryUtilizationPercentage: 85
