# Default values for scenario App.
reloader:
  enabled: false

secrets:
  enabled: true

image:
  repository: qasymphony/scenario
  pullPolicy: IfNotPresent
  tag: "3.3.4"

deployment:
  annotations: {}

service:
  type: LoadBalancer
  port: 6080
  targetPort: 6080
  servicename: qtest-scenario-service
  annotations: {}

qTestScenario:
  qTestScenarioDBName: scenario
  qTestScenarioDBUserName: postgres
  qTestScenarioDBPwd: Y2hhbmdlbWU=
  qTestScenarioDBHostName: postgres.local
  qTestScenarioPort: "6080"
  qTestScenarioLocalBaseURL: https://scenario.local
  qTestScenarioNodeTLSRejectUnAuthorized: "0"
  qTestScenarioNodeEnvironment: production
  qTestScenarioRefreshTokenSecret: ""
  qTestScenarioAppKeyDescriptor: ""
  qTestScenarioQTestURL: https://nephele.qtest.local

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  canary:
    annotations: {}
  labels: {}
  hosts:
    - scenario.local
  paths:
    - /
  extraPaths:
    []
  tls:
    []
  https: false

# VPA values
vpaAutoscaling:
  enabled: false
  updatePolicy:
    updateMode: "Off"
# HPA values
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  healthApiPath: /atlassian-connect.json
  periodSeconds: 30
  failureThreshold: 4
  targetCPUUtilizationPercentage: 85
  targetMemoryUtilizationPercentage: 85
