apiVersion: apps/v1
kind: Deployment
metadata:
  name: qtest-parameters
spec:
  replicas: {{ .Values.autoscaling.minReplicas }}
  selector:
    matchLabels:
      app: qtest-parameters
  template:
    metadata:
      labels:
        app: qtest-parameters
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}
          livenessProbe:
            httpGet:
              path: {{ .Values.autoscaling.healthApiPath }}
              port: {{ .Values.service.targetPort }}
            periodSeconds: {{ .Values.autoscaling.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.autoscaling.healthApiPath }}
              port: {{ .Values.service.targetPort }}
            periodSeconds: {{ .Values.autoscaling.periodSeconds }}
          startupProbe:
            httpGet:
              path: {{ .Values.autoscaling.healthApiPath }}
              port: {{ .Values.service.targetPort }}
            failureThreshold: {{ .Values.autoscaling.failureThreshold }}
            periodSeconds: {{ .Values.autoscaling.periodSeconds }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          env:
            - name: PG_URL
              valueFrom:
                configMapKeyRef:
                  name: qtest-parameters-configmap
                  key: qTestParametersPGUrl
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              valueFrom:
                configMapKeyRef:
                  name: qtest-parameters-configmap
                  key: qTestParametersNodeTLSRejectUnAuthorized
            - name: QTEST_HOST
              valueFrom:
                configMapKeyRef:
                  name: qtest-parameters-configmap
                  key: qTestParametersQTestHost
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: qtest-parameters-configmap
                  key: qTestParametersNodeEnv
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: qtest-parameters-configmap
                  key: qTestParametersPort
          volumeMounts:
          - name: qtest-parameter-logs
            mountPath: /usr/local/parameters/logs
      volumes:
        - name: qtest-parameter-logs
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "qtest-parameters.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}