apiVersion: apps/v1
kind: Deployment
metadata:
  name: qtest-pulse
spec:
  replicas: {{ .Values.autoscaling.minReplicas }}
  selector:
    matchLabels:
      app: qtest-pulse
  template:
    metadata:
      labels:
        app: qtest-pulse
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}
          livenessProbe:
            httpGet:
              path: {{ .Values.autoscaling.healthApiPath }}
              port: {{ .Values.service.targetPort }}
            periodSeconds: {{ .Values.autoscaling.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.autoscaling.healthApiPath }}
              port: {{ .Values.service.targetPort }}
            periodSeconds: {{ .Values.autoscaling.periodSeconds }}
          startupProbe:
            httpGet:
              path: {{ .Values.autoscaling.healthApiPath }}
              port: {{ .Values.service.targetPort }}
            failureThreshold: {{ .Values.autoscaling.failureThreshold }}
            periodSeconds: {{ .Values.autoscaling.periodSeconds }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: qtest-pulse-configmap
                  key: qTestPulseNodeEnv
            - name: PG_URL
              valueFrom:
                configMapKeyRef:
                  name: qtest-pulse-configmap
                  key: qTestPulsePGUrl
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: qtest-pulse-configmap
                  key: qTestPulsePort
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              valueFrom:
                configMapKeyRef:
                  name: qtest-pulse-configmap
                  key: qTestPulseNodeTLSRejectUnAuthorized
            - name: ROOT_URL
              valueFrom:
                configMapKeyRef:
                  name: qtest-pulse-configmap
                  key: qTestPulseRootURL
            - name: QTEST_URL
              valueFrom:
                configMapKeyRef:
                  name: qtest-pulse-configmap
                  key: qTestPulseQTestURL
            - name: SCENARIO_URL
              valueFrom:
                configMapKeyRef:
                  name: qtest-pulse-configmap
                  key: qTestPulseScenarioURL
