# Default values for qtest-pulse-chart.
reloader:
  enabled: false

secrets:
  enabled: true

image:
  repository: qasymphony/pulse
  pullPolicy: IfNotPresent
  tag: "9.3.5"

deployment:
  annotations: {}

service:
  type: LoadBalancer
  port: 4080
  targetPort: 4080
  servicename: qtest-pulse-service

qTestPulse:
  qTestPulseDBName: pulse
  qTestPulseDBUserName: postgres
  qTestPulseDBPwd: Y2hhbmdlbWU=
  qTestPulseDBHostName: postgres.local
  qTestPulsePort: "4080"
  qTestPulseNodeEnv: production
  qTestPulseRootURL: https://pulse.local
  qTestPulseQTestURL: https://nephele.qtest.local
  qTestPulseScenarioURL: https://scenario.local
  qTestPulseNodeTLSRejectUnAuthorized: "0"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  canary:
    annotations: {}
  labels: {}
  hosts:
    - pulse.local
  paths:
    - /
  extraPaths:
    []
  tls:
    []
  https: false
# VPA values
vpaAutoscaling:
  enabled: false
  updatePolicy:
    updateMode: "Off"
# HPA values
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  healthApiPath: /
  periodSeconds: 30
  failureThreshold: 4
  targetCPUUtilizationPercentage: 85
  targetMemoryUtilizationPercentage: 85
