# Default values for qtest-session-chart.

image:
  repository: qasymphony/sessions
  pullPolicy: IfNotPresent
  tag: "4.3.8"

serviceAccount:
  create: true
  name:
  annotations: {}
  automountsatoken: false

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080
  servicename: qtest-session-service

qTestSession:
  qTestSessionJSHome: /usr/local/sessions-js
  qTestSessionNodeEnvironment: production
  qTestSessionPort: "8080"
  qTestSessionDBConnection: postgresql://postgres:changeme@postgres.local/sessions
  qTestManagerHost: http://qtestdev1.container-dev.qtestdev.com
  qTestSessionMasterToken: ""
  qTestSessionStorageType: disk_storage
  qTestSessionStorageRootPath: /data
  qTestSessionSecretKey: ""

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  canary:
    annotations: {}
  labels: {}
  hosts:
    - session.container-dev.qtestdev.com
  paths:
    - /
  extraPaths:
    []
  tls:
    []
  https: false

persistence:
  enabled: false
  ## Set annotations on pvc
  annotations: {}

  ## Specify an existing volume claim instead of creating a new one.
  ## When using this option all following options like storageClass, accessMode and size are ignored.
  # existingClaim:

  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass:
  accessMode: ReadWriteOnce
  size: 5Gi

  ## Specify extra volumes. Refer to ".spec.volumes" specification : https://kubernetes.io/fr/docs/concepts/storage/volumes/
  volumes: []
  ## Specify extra mounts. Refer to ".spec.containers.volumeMounts" specification : https://kubernetes.io/fr/docs/concepts/storage/volumes/
  mounts: []

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  healthApiPath: /health-check
  periodSeconds: 30
  failureThreshold: 4
  targetCPUUtilizationPercentage: 85
  targetMemoryUtilizationPercentage: 85
